# Generated by Django 5.0.7 on 2024-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_options_carmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
