# Generated by Django 5.0.8 on 2024-08-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='auto_park',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
    ]
