# Generated by Django 5.0.7 on 2024-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_brand_alter_carmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('HatchBack', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep')], default='Jepp', max_length=9),
            preserve_default=False,
        ),
    ]
